[build]
  command = "cd facturation && npm install && npm run build"
  publish = "facturation/dist"
  functions = "facturation/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
